export const dashboardPage = String.raw`<!doctype html>
<html lang="it">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow">
  <title>Statistiche — Mattia Manzi</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/stats.css"><script src="/stats.js" defer></script>
</head>
<body class="dashboard-body">
  <a class="skip-link" href="#panoramica">Vai alle statistiche</a>
  <aside class="sidebar">
    <a class="stats-brand" href="/"><span class="brand-mark" aria-hidden="true">m.</span><span>Mattia Manzi<small>Statistiche del sito</small></span></a>
    <p class="sidebar-label">Il tuo portfolio</p>
    <nav aria-label="Sezioni delle statistiche"><a href="#panoramica">Panoramica <span>01</span></a><a href="#paesi">Paesi <span>02</span></a><a href="#dispositivi">Dispositivi <span>03</span></a><a href="#provenienza">Provenienza <span>04</span></a><a href="#contatti">Contatti <span>05</span></a></nav>
    <div class="sidebar-bottom"><a href="/" target="_blank" rel="noopener noreferrer">Apri il sito <span aria-hidden="true">↗</span></a><button id="logout" type="button">Esci dal pannello <span aria-hidden="true">↗</span></button><p>Area riservata a te.<br>I numeri restano qui.</p></div>
  </aside>
  <main class="dashboard-main" id="panoramica">
    <header class="dashboard-header"><div><p class="eyebrow">Mattia Manzi / Analisi del traffico</p><h1>Il tuo sito,<br><em>in numeri.</em></h1><p class="subtitle">Scopri chi arriva, da dove e come esplora il tuo lavoro.</p></div><div class="header-actions"><label class="period-label" for="period">Periodo</label><select id="period"><option value="1">Oggi</option><option value="7" selected>Ultimi 7 giorni</option><option value="30">Ultimi 30 giorni</option><option value="90">Ultimi 90 giorni</option></select><div><button class="quiet-button" id="refresh" type="button">Aggiorna ↻</button><button class="quiet-button" id="export" type="button" disabled>Esporta CSV ↗</button></div></div></header>
    <div class="toolbar"><span class="live-status" id="live-status" role="status">Caricamento dei dati…</span><div class="filters"><label for="country-filter">Paese</label><select id="country-filter"><option value="">Tutti i Paesi</option></select><label for="device-filter">Dispositivo</label><select id="device-filter"><option value="">Tutti</option><option value="desktop">Computer</option><option value="mobile">Smartphone</option><option value="tablet">Tablet</option><option value="unknown">Non rilevato</option></select><button id="reset-filters" type="button" hidden>Azzera filtri</button></div></div>
    <div id="error-banner" class="error-banner" role="alert" hidden></div>
    <section class="kpi-grid" aria-label="Numeri principali"><article><p>Visualizzazioni</p><strong id="kpi-views">—</strong><small>Caricamenti della pagina</small></article><article><p>Paesi raggiunti</p><strong id="kpi-countries">—</strong><small>Provenienza geografica stimata</small></article><article><p>Da smartphone</p><strong id="kpi-mobile">—</strong><small>Sul totale delle visualizzazioni</small></article><article><p>Clic sui contatti</p><strong id="kpi-contacts">—</strong><small>WhatsApp, email e telefono</small></article></section>
    <section class="panel trend-panel" aria-labelledby="trend-title"><div class="panel-head"><div><p class="eyebrow">Il ritmo del sito</p><h2 id="trend-title">Accessi nel tempo.</h2></div><span id="range-label">—</span></div><div class="chart-area" id="trend-chart"><p class="empty">I dati stanno arrivando…</p></div><div class="chart-legend"><span><i></i> Visualizzazioni giornaliere</span><span id="timezone-note">Orario italiano</span></div></section>
    <div class="two-columns"><section class="panel countries-panel" id="paesi" aria-labelledby="countries-title"><div class="panel-head"><div><p class="eyebrow">Da dove ti scoprono</p><h2 id="countries-title">Il mondo, più vicino.</h2></div><span class="panel-number">02</span></div><div class="table-wrap"><table><caption class="sr-only">Visualizzazioni per Paese</caption><thead><tr><th>Paese</th><th>Visualizzazioni</th><th>Quota</th></tr></thead><tbody id="countries-table"><tr><td colspan="3" class="empty">Caricamento…</td></tr></tbody></table></div></section>
    <section class="panel devices-panel" id="dispositivi" aria-labelledby="devices-title"><div class="panel-head"><div><p class="eyebrow">Come si collegano</p><h2 id="devices-title">Ogni schermo conta.</h2></div><span class="panel-number">03</span></div><div id="device-chart" class="device-chart"><p class="empty">Caricamento…</p></div><div id="device-legend" class="device-legend"></div><div class="browser-heading"><h3>Browser utilizzati</h3></div><div id="browser-list" class="rank-list"></div></section></div>
    <section class="panel" id="provenienza" aria-labelledby="source-title"><div class="panel-head"><div><p class="eyebrow">Il primo passo verso il sito</p><h2 id="source-title">Come arrivano qui.</h2></div><span class="panel-number">04</span></div><div id="source-list" class="source-list"><p class="empty">Caricamento…</p></div><p class="panel-note">Le visite dirette e quelle senza provenienza disponibile sono raggruppate. I link con utm_source aiutano a distinguere Instagram, WhatsApp e le altre campagne.</p></section>
    <section class="panel contacts-panel" id="contatti" aria-labelledby="contacts-title"><div class="panel-head"><div><p class="eyebrow">Dall’interesse al contatto</p><h2 id="contacts-title">Una conversazione inizia.</h2></div><span class="panel-number">05</span></div><div id="contact-list" class="contact-list"><article><span>WhatsApp ↗</span><strong>—</strong><small>Clic</small></article><article><span>Email ↗</span><strong>—</strong><small>Clic</small></article><article><span>Telefono ↗</span><strong>—</strong><small>Clic</small></article></div><p class="panel-note">Un clic apre il canale di contatto; non conferma l’invio di un messaggio o una chiamata completata.</p></section>
    <footer class="dashboard-footer"><label class="self-exclusion"><input id="exclude-self" type="checkbox"> Escludi questo browser dai conteggi</label><p id="exclusion-note">Gli accessi autenticati al pannello sono sempre esclusi.</p><div class="measurement-note"><span>Numeri chiari, senza inseguire le persone.</span><p>Visualizzazioni significa caricamenti, non persone uniche. La posizione è una stima per Paese. Nessun IP completo o identificativo di visitatore è salvato nei dati delle visite. Le preferenze DNT e GPC vengono rispettate.</p></div></footer>
  </main>
</body>
</html>
`;
