const setupMessages={
  database_missing:'Il database delle statistiche non è collegato a questa versione. Nel Worker Cloudflare verifica il collegamento D1 con nome <code>DB</code>.',
  password_missing:'La password non è presente su questa versione. In Impostazioni → Variabili e segreti, aggiungi un Segreto chiamato esattamente <code>ANALYTICS_ADMIN_PASSWORD</code>, poi distribuisci la modifica.',
  password_short:'La password impostata è troppo corta: servono almeno <strong>16 caratteri</strong>. Modifica il Segreto <code>ANALYTICS_ADMIN_PASSWORD</code> e distribuisci la modifica.'
};
export function loginPage(ready,issues=[]) {
  const setup=ready?'':issues.filter(issue=>Object.hasOwn(setupMessages,issue)).map(issue=>'<p>'+setupMessages[issue]+'</p>').join('');
  return `<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Accesso statistiche — Mattia Manzi</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/stats.css"><script src="/stats-login.js" defer></script></head><body class="login-body"><main class="login-card"><a class="stats-brand" href="/" aria-label="Torna al sito"><span class="brand-mark">m.</span><span>Mattia Manzi <small>Statistiche del sito</small></span></a><span class="eyebrow">Area riservata</span><h1>Il tuo sito,<br><em>in numeri.</em></h1><p>${ready?'Accedi per vedere come le persone scoprono il tuo lavoro.':'Il pannello non è ancora attivo.'}</p>${setup}${ready?'<form id="login-form"><label for="password">Password del pannello</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="1024"><button class="primary" type="submit">Accedi alle statistiche <span aria-hidden="true">↗</span></button><p id="login-error" class="form-error" role="alert"></p></form>':''}<a class="back-link" href="/">← Torna al portfolio</a></main></body></html>`;
}
